project:
  type: website
  output-dir: docs

website:
  title: "PA DEP Lab"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Script sections"
        contents: 
          - index.qmd
          - data.qmd
          - visualizations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

