project:
  type: website
  output-dir: docs

website:
  title: "PA DEP Lab - PM2.5 vs. Wind Speed"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

